// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: steamdatagram_messages_auth.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "steamdatagram_messages_auth.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CMsgSteamDatagramRelayAuthTicket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMsgSteamDatagramRelayAuthTicket_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMsgSteamDatagramRelayAuthTicket_ExtraField_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMsgSteamDatagramRelayAuthTicket_ExtraField_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMsgSteamDatagramSignedRelayAuthTicket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMsgSteamDatagramSignedRelayAuthTicket_reflection_ = NULL;
const ::google::protobuf::Descriptor* CMsgSteamDatagramCachedCredentialsForApp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CMsgSteamDatagramCachedCredentialsForApp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_steamdatagram_5fmessages_5fauth_2eproto() {
  protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "steamdatagram_messages_auth.proto");
  GOOGLE_CHECK(file != NULL);
  CMsgSteamDatagramRelayAuthTicket_descriptor_ = file->message_type(0);
  static const int CMsgSteamDatagramRelayAuthTicket_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, time_expiry_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, authorized_steam_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, authorized_public_ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, gameserver_steam_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, legacy_gameserver_net_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, gameserver_address_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, legacy_signature_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, app_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, legacy_gameserver_pop_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, virtual_port_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, extra_fields_),
  };
  CMsgSteamDatagramRelayAuthTicket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CMsgSteamDatagramRelayAuthTicket_descriptor_,
      CMsgSteamDatagramRelayAuthTicket::default_instance_,
      CMsgSteamDatagramRelayAuthTicket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CMsgSteamDatagramRelayAuthTicket));
  CMsgSteamDatagramRelayAuthTicket_ExtraField_descriptor_ = CMsgSteamDatagramRelayAuthTicket_descriptor_->nested_type(0);
  static const int CMsgSteamDatagramRelayAuthTicket_ExtraField_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket_ExtraField, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket_ExtraField, string_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket_ExtraField, int64_value_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket_ExtraField, fixed64_value_),
  };
  CMsgSteamDatagramRelayAuthTicket_ExtraField_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CMsgSteamDatagramRelayAuthTicket_ExtraField_descriptor_,
      CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance_,
      CMsgSteamDatagramRelayAuthTicket_ExtraField_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket_ExtraField, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramRelayAuthTicket_ExtraField, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CMsgSteamDatagramRelayAuthTicket_ExtraField));
  CMsgSteamDatagramSignedRelayAuthTicket_descriptor_ = file->message_type(1);
  static const int CMsgSteamDatagramSignedRelayAuthTicket_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramSignedRelayAuthTicket, reserved_do_not_use_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramSignedRelayAuthTicket, key_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramSignedRelayAuthTicket, ticket_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramSignedRelayAuthTicket, signature_),
  };
  CMsgSteamDatagramSignedRelayAuthTicket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CMsgSteamDatagramSignedRelayAuthTicket_descriptor_,
      CMsgSteamDatagramSignedRelayAuthTicket::default_instance_,
      CMsgSteamDatagramSignedRelayAuthTicket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramSignedRelayAuthTicket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramSignedRelayAuthTicket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CMsgSteamDatagramSignedRelayAuthTicket));
  CMsgSteamDatagramCachedCredentialsForApp_descriptor_ = file->message_type(2);
  static const int CMsgSteamDatagramCachedCredentialsForApp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramCachedCredentialsForApp, private_key_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramCachedCredentialsForApp, cert_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramCachedCredentialsForApp, relay_tickets_),
  };
  CMsgSteamDatagramCachedCredentialsForApp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CMsgSteamDatagramCachedCredentialsForApp_descriptor_,
      CMsgSteamDatagramCachedCredentialsForApp::default_instance_,
      CMsgSteamDatagramCachedCredentialsForApp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramCachedCredentialsForApp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CMsgSteamDatagramCachedCredentialsForApp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CMsgSteamDatagramCachedCredentialsForApp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_steamdatagram_5fmessages_5fauth_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CMsgSteamDatagramRelayAuthTicket_descriptor_, &CMsgSteamDatagramRelayAuthTicket::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CMsgSteamDatagramRelayAuthTicket_ExtraField_descriptor_, &CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CMsgSteamDatagramSignedRelayAuthTicket_descriptor_, &CMsgSteamDatagramSignedRelayAuthTicket::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CMsgSteamDatagramCachedCredentialsForApp_descriptor_, &CMsgSteamDatagramCachedCredentialsForApp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_steamdatagram_5fmessages_5fauth_2eproto() {
  delete CMsgSteamDatagramRelayAuthTicket::default_instance_;
  delete CMsgSteamDatagramRelayAuthTicket_reflection_;
  delete CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance_;
  delete CMsgSteamDatagramRelayAuthTicket_ExtraField_reflection_;
  delete CMsgSteamDatagramSignedRelayAuthTicket::default_instance_;
  delete CMsgSteamDatagramSignedRelayAuthTicket_reflection_;
  delete CMsgSteamDatagramCachedCredentialsForApp::default_instance_;
  delete CMsgSteamDatagramCachedCredentialsForApp_reflection_;
}

void protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!steamdatagram_messages_auth.proto\"\321\003\n "
    "CMsgSteamDatagramRelayAuthTicket\022\023\n\013time"
    "_expiry\030\001 \001(\007\022\033\n\023authorized_steam_id\030\002 \001"
    "(\006\022\034\n\024authorized_public_ip\030\003 \001(\007\022\033\n\023game"
    "server_steam_id\030\004 \001(\006\022 \n\030legacy_gameserv"
    "er_net_id\030\005 \001(\006\022\032\n\022gameserver_address\030\013 "
    "\001(\t\022\030\n\020legacy_signature\030\006 \001(\014\022\016\n\006app_id\030"
    "\007 \001(\r\022 \n\030legacy_gameserver_pop_id\030\t \001(\007\022"
    "\024\n\014virtual_port\030\n \001(\r\022B\n\014extra_fields\030\010 "
    "\003(\0132,.CMsgSteamDatagramRelayAuthTicket.E"
    "xtraField\032\\\n\nExtraField\022\014\n\004name\030\001 \001(\t\022\024\n"
    "\014string_value\030\002 \001(\t\022\023\n\013int64_value\030\003 \001(\022"
    "\022\025\n\rfixed64_value\030\005 \001(\006\"x\n&CMsgSteamData"
    "gramSignedRelayAuthTicket\022\033\n\023reserved_do"
    "_not_use\030\001 \001(\006\022\016\n\006key_id\030\002 \001(\006\022\016\n\006ticket"
    "\030\003 \001(\014\022\021\n\tsignature\030\004 \001(\014\"d\n(CMsgSteamDa"
    "tagramCachedCredentialsForApp\022\023\n\013private"
    "_key\030\001 \001(\014\022\014\n\004cert\030\002 \001(\014\022\025\n\rrelay_ticket"
    "s\030\003 \003(\014B\003\200\001\000", 732);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "steamdatagram_messages_auth.proto", &protobuf_RegisterTypes);
  CMsgSteamDatagramRelayAuthTicket::default_instance_ = new CMsgSteamDatagramRelayAuthTicket();
  CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance_ = new CMsgSteamDatagramRelayAuthTicket_ExtraField();
  CMsgSteamDatagramSignedRelayAuthTicket::default_instance_ = new CMsgSteamDatagramSignedRelayAuthTicket();
  CMsgSteamDatagramCachedCredentialsForApp::default_instance_ = new CMsgSteamDatagramCachedCredentialsForApp();
  CMsgSteamDatagramRelayAuthTicket::default_instance_->InitAsDefaultInstance();
  CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance_->InitAsDefaultInstance();
  CMsgSteamDatagramSignedRelayAuthTicket::default_instance_->InitAsDefaultInstance();
  CMsgSteamDatagramCachedCredentialsForApp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_steamdatagram_5fmessages_5fauth_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_steamdatagram_5fmessages_5fauth_2eproto {
  StaticDescriptorInitializer_steamdatagram_5fmessages_5fauth_2eproto() {
    protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto();
  }
} static_descriptor_initializer_steamdatagram_5fmessages_5fauth_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CMsgSteamDatagramRelayAuthTicket_ExtraField::kNameFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket_ExtraField::kStringValueFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket_ExtraField::kInt64ValueFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket_ExtraField::kFixed64ValueFieldNumber;
#endif  // !_MSC_VER

CMsgSteamDatagramRelayAuthTicket_ExtraField::CMsgSteamDatagramRelayAuthTicket_ExtraField()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::InitAsDefaultInstance() {
}

CMsgSteamDatagramRelayAuthTicket_ExtraField::CMsgSteamDatagramRelayAuthTicket_ExtraField(const CMsgSteamDatagramRelayAuthTicket_ExtraField& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  string_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  int64_value_ = GOOGLE_LONGLONG(0);
  fixed64_value_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgSteamDatagramRelayAuthTicket_ExtraField::~CMsgSteamDatagramRelayAuthTicket_ExtraField() {
  SharedDtor();
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (string_value_ != &::google::protobuf::internal::kEmptyString) {
    delete string_value_;
  }
  if (this != default_instance_) {
  }
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMsgSteamDatagramRelayAuthTicket_ExtraField::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMsgSteamDatagramRelayAuthTicket_ExtraField_descriptor_;
}

const CMsgSteamDatagramRelayAuthTicket_ExtraField& CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto();
  return *default_instance_;
}

CMsgSteamDatagramRelayAuthTicket_ExtraField* CMsgSteamDatagramRelayAuthTicket_ExtraField::default_instance_ = NULL;

CMsgSteamDatagramRelayAuthTicket_ExtraField* CMsgSteamDatagramRelayAuthTicket_ExtraField::New() const {
  return new CMsgSteamDatagramRelayAuthTicket_ExtraField;
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_string_value()) {
      if (string_value_ != &::google::protobuf::internal::kEmptyString) {
        string_value_->clear();
      }
    }
    int64_value_ = GOOGLE_LONGLONG(0);
    fixed64_value_ = GOOGLE_ULONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CMsgSteamDatagramRelayAuthTicket_ExtraField::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_string_value;
        break;
      }

      // optional string string_value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_string_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->string_value().data(), this->string_value().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_int64_value;
        break;
      }

      // optional sint64 int64_value = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_int64_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &int64_value_)));
          set_has_int64_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(41)) goto parse_fixed64_value;
        break;
      }

      // optional fixed64 fixed64_value = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_fixed64_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &fixed64_value_)));
          set_has_fixed64_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // optional string string_value = 2;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->string_value(), output);
  }

  // optional sint64 int64_value = 3;
  if (has_int64_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(3, this->int64_value(), output);
  }

  // optional fixed64 fixed64_value = 5;
  if (has_fixed64_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(5, this->fixed64_value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CMsgSteamDatagramRelayAuthTicket_ExtraField::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string string_value = 2;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->string_value().data(), this->string_value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->string_value(), target);
  }

  // optional sint64 int64_value = 3;
  if (has_int64_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt64ToArray(3, this->int64_value(), target);
  }

  // optional fixed64 fixed64_value = 5;
  if (has_fixed64_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(5, this->fixed64_value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CMsgSteamDatagramRelayAuthTicket_ExtraField::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string string_value = 2;
    if (has_string_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->string_value());
    }

    // optional sint64 int64_value = 3;
    if (has_int64_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt64Size(
          this->int64_value());
    }

    // optional fixed64 fixed64_value = 5;
    if (has_fixed64_value()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CMsgSteamDatagramRelayAuthTicket_ExtraField* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CMsgSteamDatagramRelayAuthTicket_ExtraField*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::MergeFrom(const CMsgSteamDatagramRelayAuthTicket_ExtraField& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_string_value()) {
      set_string_value(from.string_value());
    }
    if (from.has_int64_value()) {
      set_int64_value(from.int64_value());
    }
    if (from.has_fixed64_value()) {
      set_fixed64_value(from.fixed64_value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::CopyFrom(const CMsgSteamDatagramRelayAuthTicket_ExtraField& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgSteamDatagramRelayAuthTicket_ExtraField::IsInitialized() const {

  return true;
}

void CMsgSteamDatagramRelayAuthTicket_ExtraField::Swap(CMsgSteamDatagramRelayAuthTicket_ExtraField* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(string_value_, other->string_value_);
    std::swap(int64_value_, other->int64_value_);
    std::swap(fixed64_value_, other->fixed64_value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CMsgSteamDatagramRelayAuthTicket_ExtraField::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMsgSteamDatagramRelayAuthTicket_ExtraField_descriptor_;
  metadata.reflection = CMsgSteamDatagramRelayAuthTicket_ExtraField_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int CMsgSteamDatagramRelayAuthTicket::kTimeExpiryFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kAuthorizedSteamIdFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kAuthorizedPublicIpFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kGameserverSteamIdFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kLegacyGameserverNetIdFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kGameserverAddressFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kLegacySignatureFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kAppIdFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kLegacyGameserverPopIdFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kVirtualPortFieldNumber;
const int CMsgSteamDatagramRelayAuthTicket::kExtraFieldsFieldNumber;
#endif  // !_MSC_VER

CMsgSteamDatagramRelayAuthTicket::CMsgSteamDatagramRelayAuthTicket()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CMsgSteamDatagramRelayAuthTicket::InitAsDefaultInstance() {
}

CMsgSteamDatagramRelayAuthTicket::CMsgSteamDatagramRelayAuthTicket(const CMsgSteamDatagramRelayAuthTicket& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CMsgSteamDatagramRelayAuthTicket::SharedCtor() {
  _cached_size_ = 0;
  time_expiry_ = 0u;
  authorized_steam_id_ = GOOGLE_ULONGLONG(0);
  authorized_public_ip_ = 0u;
  gameserver_steam_id_ = GOOGLE_ULONGLONG(0);
  legacy_gameserver_net_id_ = GOOGLE_ULONGLONG(0);
  gameserver_address_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  legacy_signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  app_id_ = 0u;
  legacy_gameserver_pop_id_ = 0u;
  virtual_port_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgSteamDatagramRelayAuthTicket::~CMsgSteamDatagramRelayAuthTicket() {
  SharedDtor();
}

void CMsgSteamDatagramRelayAuthTicket::SharedDtor() {
  if (gameserver_address_ != &::google::protobuf::internal::kEmptyString) {
    delete gameserver_address_;
  }
  if (legacy_signature_ != &::google::protobuf::internal::kEmptyString) {
    delete legacy_signature_;
  }
  if (this != default_instance_) {
  }
}

void CMsgSteamDatagramRelayAuthTicket::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMsgSteamDatagramRelayAuthTicket::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMsgSteamDatagramRelayAuthTicket_descriptor_;
}

const CMsgSteamDatagramRelayAuthTicket& CMsgSteamDatagramRelayAuthTicket::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto();
  return *default_instance_;
}

CMsgSteamDatagramRelayAuthTicket* CMsgSteamDatagramRelayAuthTicket::default_instance_ = NULL;

CMsgSteamDatagramRelayAuthTicket* CMsgSteamDatagramRelayAuthTicket::New() const {
  return new CMsgSteamDatagramRelayAuthTicket;
}

void CMsgSteamDatagramRelayAuthTicket::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    time_expiry_ = 0u;
    authorized_steam_id_ = GOOGLE_ULONGLONG(0);
    authorized_public_ip_ = 0u;
    gameserver_steam_id_ = GOOGLE_ULONGLONG(0);
    legacy_gameserver_net_id_ = GOOGLE_ULONGLONG(0);
    if (has_gameserver_address()) {
      if (gameserver_address_ != &::google::protobuf::internal::kEmptyString) {
        gameserver_address_->clear();
      }
    }
    if (has_legacy_signature()) {
      if (legacy_signature_ != &::google::protobuf::internal::kEmptyString) {
        legacy_signature_->clear();
      }
    }
    app_id_ = 0u;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    legacy_gameserver_pop_id_ = 0u;
    virtual_port_ = 0u;
  }
  extra_fields_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CMsgSteamDatagramRelayAuthTicket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional fixed32 time_expiry = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &time_expiry_)));
          set_has_time_expiry();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_authorized_steam_id;
        break;
      }

      // optional fixed64 authorized_steam_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_authorized_steam_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &authorized_steam_id_)));
          set_has_authorized_steam_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_authorized_public_ip;
        break;
      }

      // optional fixed32 authorized_public_ip = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_authorized_public_ip:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &authorized_public_ip_)));
          set_has_authorized_public_ip();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(33)) goto parse_gameserver_steam_id;
        break;
      }

      // optional fixed64 gameserver_steam_id = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_gameserver_steam_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &gameserver_steam_id_)));
          set_has_gameserver_steam_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(41)) goto parse_legacy_gameserver_net_id;
        break;
      }

      // optional fixed64 legacy_gameserver_net_id = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_legacy_gameserver_net_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &legacy_gameserver_net_id_)));
          set_has_legacy_gameserver_net_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_legacy_signature;
        break;
      }

      // optional bytes legacy_signature = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_legacy_signature:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_legacy_signature()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_app_id;
        break;
      }

      // optional uint32 app_id = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_app_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &app_id_)));
          set_has_app_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_extra_fields;
        break;
      }

      // repeated .CMsgSteamDatagramRelayAuthTicket.ExtraField extra_fields = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_extra_fields:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_extra_fields()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(66)) goto parse_extra_fields;
        if (input->ExpectTag(77)) goto parse_legacy_gameserver_pop_id;
        break;
      }

      // optional fixed32 legacy_gameserver_pop_id = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_legacy_gameserver_pop_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED32>(
                 input, &legacy_gameserver_pop_id_)));
          set_has_legacy_gameserver_pop_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_virtual_port;
        break;
      }

      // optional uint32 virtual_port = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_virtual_port:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &virtual_port_)));
          set_has_virtual_port();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_gameserver_address;
        break;
      }

      // optional string gameserver_address = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_gameserver_address:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gameserver_address()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->gameserver_address().data(), this->gameserver_address().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CMsgSteamDatagramRelayAuthTicket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional fixed32 time_expiry = 1;
  if (has_time_expiry()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(1, this->time_expiry(), output);
  }

  // optional fixed64 authorized_steam_id = 2;
  if (has_authorized_steam_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(2, this->authorized_steam_id(), output);
  }

  // optional fixed32 authorized_public_ip = 3;
  if (has_authorized_public_ip()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(3, this->authorized_public_ip(), output);
  }

  // optional fixed64 gameserver_steam_id = 4;
  if (has_gameserver_steam_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(4, this->gameserver_steam_id(), output);
  }

  // optional fixed64 legacy_gameserver_net_id = 5;
  if (has_legacy_gameserver_net_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(5, this->legacy_gameserver_net_id(), output);
  }

  // optional bytes legacy_signature = 6;
  if (has_legacy_signature()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      6, this->legacy_signature(), output);
  }

  // optional uint32 app_id = 7;
  if (has_app_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->app_id(), output);
  }

  // repeated .CMsgSteamDatagramRelayAuthTicket.ExtraField extra_fields = 8;
  for (int i = 0; i < this->extra_fields_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, this->extra_fields(i), output);
  }

  // optional fixed32 legacy_gameserver_pop_id = 9;
  if (has_legacy_gameserver_pop_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed32(9, this->legacy_gameserver_pop_id(), output);
  }

  // optional uint32 virtual_port = 10;
  if (has_virtual_port()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->virtual_port(), output);
  }

  // optional string gameserver_address = 11;
  if (has_gameserver_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->gameserver_address().data(), this->gameserver_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      11, this->gameserver_address(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CMsgSteamDatagramRelayAuthTicket::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional fixed32 time_expiry = 1;
  if (has_time_expiry()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(1, this->time_expiry(), target);
  }

  // optional fixed64 authorized_steam_id = 2;
  if (has_authorized_steam_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(2, this->authorized_steam_id(), target);
  }

  // optional fixed32 authorized_public_ip = 3;
  if (has_authorized_public_ip()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(3, this->authorized_public_ip(), target);
  }

  // optional fixed64 gameserver_steam_id = 4;
  if (has_gameserver_steam_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(4, this->gameserver_steam_id(), target);
  }

  // optional fixed64 legacy_gameserver_net_id = 5;
  if (has_legacy_gameserver_net_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(5, this->legacy_gameserver_net_id(), target);
  }

  // optional bytes legacy_signature = 6;
  if (has_legacy_signature()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->legacy_signature(), target);
  }

  // optional uint32 app_id = 7;
  if (has_app_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->app_id(), target);
  }

  // repeated .CMsgSteamDatagramRelayAuthTicket.ExtraField extra_fields = 8;
  for (int i = 0; i < this->extra_fields_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, this->extra_fields(i), target);
  }

  // optional fixed32 legacy_gameserver_pop_id = 9;
  if (has_legacy_gameserver_pop_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed32ToArray(9, this->legacy_gameserver_pop_id(), target);
  }

  // optional uint32 virtual_port = 10;
  if (has_virtual_port()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->virtual_port(), target);
  }

  // optional string gameserver_address = 11;
  if (has_gameserver_address()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->gameserver_address().data(), this->gameserver_address().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->gameserver_address(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CMsgSteamDatagramRelayAuthTicket::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional fixed32 time_expiry = 1;
    if (has_time_expiry()) {
      total_size += 1 + 4;
    }

    // optional fixed64 authorized_steam_id = 2;
    if (has_authorized_steam_id()) {
      total_size += 1 + 8;
    }

    // optional fixed32 authorized_public_ip = 3;
    if (has_authorized_public_ip()) {
      total_size += 1 + 4;
    }

    // optional fixed64 gameserver_steam_id = 4;
    if (has_gameserver_steam_id()) {
      total_size += 1 + 8;
    }

    // optional fixed64 legacy_gameserver_net_id = 5;
    if (has_legacy_gameserver_net_id()) {
      total_size += 1 + 8;
    }

    // optional string gameserver_address = 11;
    if (has_gameserver_address()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->gameserver_address());
    }

    // optional bytes legacy_signature = 6;
    if (has_legacy_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->legacy_signature());
    }

    // optional uint32 app_id = 7;
    if (has_app_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->app_id());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional fixed32 legacy_gameserver_pop_id = 9;
    if (has_legacy_gameserver_pop_id()) {
      total_size += 1 + 4;
    }

    // optional uint32 virtual_port = 10;
    if (has_virtual_port()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->virtual_port());
    }

  }
  // repeated .CMsgSteamDatagramRelayAuthTicket.ExtraField extra_fields = 8;
  total_size += 1 * this->extra_fields_size();
  for (int i = 0; i < this->extra_fields_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->extra_fields(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgSteamDatagramRelayAuthTicket::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CMsgSteamDatagramRelayAuthTicket* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CMsgSteamDatagramRelayAuthTicket*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMsgSteamDatagramRelayAuthTicket::MergeFrom(const CMsgSteamDatagramRelayAuthTicket& from) {
  GOOGLE_CHECK_NE(&from, this);
  extra_fields_.MergeFrom(from.extra_fields_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_time_expiry()) {
      set_time_expiry(from.time_expiry());
    }
    if (from.has_authorized_steam_id()) {
      set_authorized_steam_id(from.authorized_steam_id());
    }
    if (from.has_authorized_public_ip()) {
      set_authorized_public_ip(from.authorized_public_ip());
    }
    if (from.has_gameserver_steam_id()) {
      set_gameserver_steam_id(from.gameserver_steam_id());
    }
    if (from.has_legacy_gameserver_net_id()) {
      set_legacy_gameserver_net_id(from.legacy_gameserver_net_id());
    }
    if (from.has_gameserver_address()) {
      set_gameserver_address(from.gameserver_address());
    }
    if (from.has_legacy_signature()) {
      set_legacy_signature(from.legacy_signature());
    }
    if (from.has_app_id()) {
      set_app_id(from.app_id());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_legacy_gameserver_pop_id()) {
      set_legacy_gameserver_pop_id(from.legacy_gameserver_pop_id());
    }
    if (from.has_virtual_port()) {
      set_virtual_port(from.virtual_port());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CMsgSteamDatagramRelayAuthTicket::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMsgSteamDatagramRelayAuthTicket::CopyFrom(const CMsgSteamDatagramRelayAuthTicket& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgSteamDatagramRelayAuthTicket::IsInitialized() const {

  return true;
}

void CMsgSteamDatagramRelayAuthTicket::Swap(CMsgSteamDatagramRelayAuthTicket* other) {
  if (other != this) {
    std::swap(time_expiry_, other->time_expiry_);
    std::swap(authorized_steam_id_, other->authorized_steam_id_);
    std::swap(authorized_public_ip_, other->authorized_public_ip_);
    std::swap(gameserver_steam_id_, other->gameserver_steam_id_);
    std::swap(legacy_gameserver_net_id_, other->legacy_gameserver_net_id_);
    std::swap(gameserver_address_, other->gameserver_address_);
    std::swap(legacy_signature_, other->legacy_signature_);
    std::swap(app_id_, other->app_id_);
    std::swap(legacy_gameserver_pop_id_, other->legacy_gameserver_pop_id_);
    std::swap(virtual_port_, other->virtual_port_);
    extra_fields_.Swap(&other->extra_fields_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CMsgSteamDatagramRelayAuthTicket::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMsgSteamDatagramRelayAuthTicket_descriptor_;
  metadata.reflection = CMsgSteamDatagramRelayAuthTicket_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CMsgSteamDatagramSignedRelayAuthTicket::kReservedDoNotUseFieldNumber;
const int CMsgSteamDatagramSignedRelayAuthTicket::kKeyIdFieldNumber;
const int CMsgSteamDatagramSignedRelayAuthTicket::kTicketFieldNumber;
const int CMsgSteamDatagramSignedRelayAuthTicket::kSignatureFieldNumber;
#endif  // !_MSC_VER

CMsgSteamDatagramSignedRelayAuthTicket::CMsgSteamDatagramSignedRelayAuthTicket()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CMsgSteamDatagramSignedRelayAuthTicket::InitAsDefaultInstance() {
}

CMsgSteamDatagramSignedRelayAuthTicket::CMsgSteamDatagramSignedRelayAuthTicket(const CMsgSteamDatagramSignedRelayAuthTicket& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CMsgSteamDatagramSignedRelayAuthTicket::SharedCtor() {
  _cached_size_ = 0;
  reserved_do_not_use_ = GOOGLE_ULONGLONG(0);
  key_id_ = GOOGLE_ULONGLONG(0);
  ticket_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  signature_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgSteamDatagramSignedRelayAuthTicket::~CMsgSteamDatagramSignedRelayAuthTicket() {
  SharedDtor();
}

void CMsgSteamDatagramSignedRelayAuthTicket::SharedDtor() {
  if (ticket_ != &::google::protobuf::internal::kEmptyString) {
    delete ticket_;
  }
  if (signature_ != &::google::protobuf::internal::kEmptyString) {
    delete signature_;
  }
  if (this != default_instance_) {
  }
}

void CMsgSteamDatagramSignedRelayAuthTicket::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMsgSteamDatagramSignedRelayAuthTicket::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMsgSteamDatagramSignedRelayAuthTicket_descriptor_;
}

const CMsgSteamDatagramSignedRelayAuthTicket& CMsgSteamDatagramSignedRelayAuthTicket::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto();
  return *default_instance_;
}

CMsgSteamDatagramSignedRelayAuthTicket* CMsgSteamDatagramSignedRelayAuthTicket::default_instance_ = NULL;

CMsgSteamDatagramSignedRelayAuthTicket* CMsgSteamDatagramSignedRelayAuthTicket::New() const {
  return new CMsgSteamDatagramSignedRelayAuthTicket;
}

void CMsgSteamDatagramSignedRelayAuthTicket::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    reserved_do_not_use_ = GOOGLE_ULONGLONG(0);
    key_id_ = GOOGLE_ULONGLONG(0);
    if (has_ticket()) {
      if (ticket_ != &::google::protobuf::internal::kEmptyString) {
        ticket_->clear();
      }
    }
    if (has_signature()) {
      if (signature_ != &::google::protobuf::internal::kEmptyString) {
        signature_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CMsgSteamDatagramSignedRelayAuthTicket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional fixed64 reserved_do_not_use = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &reserved_do_not_use_)));
          set_has_reserved_do_not_use();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(17)) goto parse_key_id;
        break;
      }

      // optional fixed64 key_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED64) {
         parse_key_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &key_id_)));
          set_has_key_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_ticket;
        break;
      }

      // optional bytes ticket = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ticket:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_ticket()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_signature;
        break;
      }

      // optional bytes signature = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_signature:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_signature()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CMsgSteamDatagramSignedRelayAuthTicket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional fixed64 reserved_do_not_use = 1;
  if (has_reserved_do_not_use()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(1, this->reserved_do_not_use(), output);
  }

  // optional fixed64 key_id = 2;
  if (has_key_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(2, this->key_id(), output);
  }

  // optional bytes ticket = 3;
  if (has_ticket()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->ticket(), output);
  }

  // optional bytes signature = 4;
  if (has_signature()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      4, this->signature(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CMsgSteamDatagramSignedRelayAuthTicket::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional fixed64 reserved_do_not_use = 1;
  if (has_reserved_do_not_use()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(1, this->reserved_do_not_use(), target);
  }

  // optional fixed64 key_id = 2;
  if (has_key_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(2, this->key_id(), target);
  }

  // optional bytes ticket = 3;
  if (has_ticket()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->ticket(), target);
  }

  // optional bytes signature = 4;
  if (has_signature()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->signature(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CMsgSteamDatagramSignedRelayAuthTicket::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional fixed64 reserved_do_not_use = 1;
    if (has_reserved_do_not_use()) {
      total_size += 1 + 8;
    }

    // optional fixed64 key_id = 2;
    if (has_key_id()) {
      total_size += 1 + 8;
    }

    // optional bytes ticket = 3;
    if (has_ticket()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->ticket());
    }

    // optional bytes signature = 4;
    if (has_signature()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->signature());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgSteamDatagramSignedRelayAuthTicket::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CMsgSteamDatagramSignedRelayAuthTicket* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CMsgSteamDatagramSignedRelayAuthTicket*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMsgSteamDatagramSignedRelayAuthTicket::MergeFrom(const CMsgSteamDatagramSignedRelayAuthTicket& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_reserved_do_not_use()) {
      set_reserved_do_not_use(from.reserved_do_not_use());
    }
    if (from.has_key_id()) {
      set_key_id(from.key_id());
    }
    if (from.has_ticket()) {
      set_ticket(from.ticket());
    }
    if (from.has_signature()) {
      set_signature(from.signature());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CMsgSteamDatagramSignedRelayAuthTicket::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMsgSteamDatagramSignedRelayAuthTicket::CopyFrom(const CMsgSteamDatagramSignedRelayAuthTicket& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgSteamDatagramSignedRelayAuthTicket::IsInitialized() const {

  return true;
}

void CMsgSteamDatagramSignedRelayAuthTicket::Swap(CMsgSteamDatagramSignedRelayAuthTicket* other) {
  if (other != this) {
    std::swap(reserved_do_not_use_, other->reserved_do_not_use_);
    std::swap(key_id_, other->key_id_);
    std::swap(ticket_, other->ticket_);
    std::swap(signature_, other->signature_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CMsgSteamDatagramSignedRelayAuthTicket::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMsgSteamDatagramSignedRelayAuthTicket_descriptor_;
  metadata.reflection = CMsgSteamDatagramSignedRelayAuthTicket_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int CMsgSteamDatagramCachedCredentialsForApp::kPrivateKeyFieldNumber;
const int CMsgSteamDatagramCachedCredentialsForApp::kCertFieldNumber;
const int CMsgSteamDatagramCachedCredentialsForApp::kRelayTicketsFieldNumber;
#endif  // !_MSC_VER

CMsgSteamDatagramCachedCredentialsForApp::CMsgSteamDatagramCachedCredentialsForApp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void CMsgSteamDatagramCachedCredentialsForApp::InitAsDefaultInstance() {
}

CMsgSteamDatagramCachedCredentialsForApp::CMsgSteamDatagramCachedCredentialsForApp(const CMsgSteamDatagramCachedCredentialsForApp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void CMsgSteamDatagramCachedCredentialsForApp::SharedCtor() {
  _cached_size_ = 0;
  private_key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CMsgSteamDatagramCachedCredentialsForApp::~CMsgSteamDatagramCachedCredentialsForApp() {
  SharedDtor();
}

void CMsgSteamDatagramCachedCredentialsForApp::SharedDtor() {
  if (private_key_ != &::google::protobuf::internal::kEmptyString) {
    delete private_key_;
  }
  if (cert_ != &::google::protobuf::internal::kEmptyString) {
    delete cert_;
  }
  if (this != default_instance_) {
  }
}

void CMsgSteamDatagramCachedCredentialsForApp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CMsgSteamDatagramCachedCredentialsForApp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CMsgSteamDatagramCachedCredentialsForApp_descriptor_;
}

const CMsgSteamDatagramCachedCredentialsForApp& CMsgSteamDatagramCachedCredentialsForApp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_steamdatagram_5fmessages_5fauth_2eproto();
  return *default_instance_;
}

CMsgSteamDatagramCachedCredentialsForApp* CMsgSteamDatagramCachedCredentialsForApp::default_instance_ = NULL;

CMsgSteamDatagramCachedCredentialsForApp* CMsgSteamDatagramCachedCredentialsForApp::New() const {
  return new CMsgSteamDatagramCachedCredentialsForApp;
}

void CMsgSteamDatagramCachedCredentialsForApp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_private_key()) {
      if (private_key_ != &::google::protobuf::internal::kEmptyString) {
        private_key_->clear();
      }
    }
    if (has_cert()) {
      if (cert_ != &::google::protobuf::internal::kEmptyString) {
        cert_->clear();
      }
    }
  }
  relay_tickets_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CMsgSteamDatagramCachedCredentialsForApp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes private_key = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_private_key()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_cert;
        break;
      }

      // optional bytes cert = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cert:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_cert()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_relay_tickets;
        break;
      }

      // repeated bytes relay_tickets = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_relay_tickets:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_relay_tickets()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_relay_tickets;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void CMsgSteamDatagramCachedCredentialsForApp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional bytes private_key = 1;
  if (has_private_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->private_key(), output);
  }

  // optional bytes cert = 2;
  if (has_cert()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->cert(), output);
  }

  // repeated bytes relay_tickets = 3;
  for (int i = 0; i < this->relay_tickets_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->relay_tickets(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* CMsgSteamDatagramCachedCredentialsForApp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional bytes private_key = 1;
  if (has_private_key()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->private_key(), target);
  }

  // optional bytes cert = 2;
  if (has_cert()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->cert(), target);
  }

  // repeated bytes relay_tickets = 3;
  for (int i = 0; i < this->relay_tickets_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(3, this->relay_tickets(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int CMsgSteamDatagramCachedCredentialsForApp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional bytes private_key = 1;
    if (has_private_key()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->private_key());
    }

    // optional bytes cert = 2;
    if (has_cert()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->cert());
    }

  }
  // repeated bytes relay_tickets = 3;
  total_size += 1 * this->relay_tickets_size();
  for (int i = 0; i < this->relay_tickets_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->relay_tickets(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CMsgSteamDatagramCachedCredentialsForApp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CMsgSteamDatagramCachedCredentialsForApp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CMsgSteamDatagramCachedCredentialsForApp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CMsgSteamDatagramCachedCredentialsForApp::MergeFrom(const CMsgSteamDatagramCachedCredentialsForApp& from) {
  GOOGLE_CHECK_NE(&from, this);
  relay_tickets_.MergeFrom(from.relay_tickets_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_private_key()) {
      set_private_key(from.private_key());
    }
    if (from.has_cert()) {
      set_cert(from.cert());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CMsgSteamDatagramCachedCredentialsForApp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CMsgSteamDatagramCachedCredentialsForApp::CopyFrom(const CMsgSteamDatagramCachedCredentialsForApp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgSteamDatagramCachedCredentialsForApp::IsInitialized() const {

  return true;
}

void CMsgSteamDatagramCachedCredentialsForApp::Swap(CMsgSteamDatagramCachedCredentialsForApp* other) {
  if (other != this) {
    std::swap(private_key_, other->private_key_);
    std::swap(cert_, other->cert_);
    relay_tickets_.Swap(&other->relay_tickets_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CMsgSteamDatagramCachedCredentialsForApp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CMsgSteamDatagramCachedCredentialsForApp_descriptor_;
  metadata.reflection = CMsgSteamDatagramCachedCredentialsForApp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
